apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: data-conversion-development
resources:
- ../base
- namespace.yaml
- flask-ingress.yaml
images:
- name: flask
  newName: ghcr.io/psdi-uk/psdi-data-conversion/data-conversion
  newTag: 0.0.1
