---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: data-conversion-admin-role-binding
subjects:
- kind: ServiceAccount
  name: data-conversion-admin-sa
roleRef:
  kind: Role
  name: data-conversion-admin-role
  apiGroup: rbac.authorization.k8s.io
