apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- data-conversion-admin-role-binding.yml
- data-conversion-admin-role.yml
- data-conversion-sa-secret.yml
- data-conversion-sa.yml
- flask-deployment.yml
- flask-service.yml
