# Workflow for manually triggering deployment of latest release version to the production environment

# It is intended that this workflow be manually triggered after the 'ci-release.yml' job has been shown
# to successfully deploy the latest release version to the staging cluster.

# To be more specific, this workflow deploys the container in the GitHub Container Registry namespace for this
# repo whose tag corresponds to the highest version number, while only considering tags of the form 'v*.*.*',
# where '*' signify non-negative integers.

name: CI - Deploy to production cluster
run-name: CI - Deploy to production cluster
on:
  workflow_dispatch:
  # >>>>>>>>>>>>>>> MODIFICATION FOR TESTING PURPOSES: added push: because workflow_dispatch only is not supported in non-main branches <<<<<<<<<<<<<<<
  push:

jobs:

  deploy-stfc-production-k8s:
    # run on our self hosted github runners enabling access to STFC infrastructure
    runs-on: psdi-uk-runners 
    steps:
    - name: Install jq
      run: |
        sudo apt-get install jq
    - name: Setup docker auth
      run: |
        mkdir -p ~/.docker
        cat <<EOF > ~/.docker/config.json
        {
          "auths": {
            "ghcr.io": {
              "auth": "$(echo -n "$GIT_USERNAME:$GIT_PASSWORD" | base64 -w0)"
            }
          }
        }
        EOF
      env: # needed to authenticate to github and download the repo
        GIT_USERNAME: ${{ github.actor }}
        GIT_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
    - name: Get latest tag in the relase branch
      run: |
        # Use GitHub CR API to get list of all tags
        RESPONSE=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/v2/container/ghcr.io/psdi-uk/psdi-data-conversion/data-conversion/tags")
        # Extract only the tags corresponding to releases, i.e. of the form 'v*.*.*'
        TAGS=$(echo "$RESPONSE" | jq -r '.[].name' | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+')
        # Find the highest version number
        TARGET_TAG=$(echo "$TAGS" | sort -V | tail -n 1)
        echo "TARGET_TAG=$TARGET_TAG" >> $GITHUB_ENV # Make 'TARGET_TAG' available in future steps via 'env.TARGET_TAG'
      env: # needed to authenticate to GitHub CR API
        GIT_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
    - name: Deploy container with tag to production environment
      uses: ./.github/workflows/job-deploy-k8s.yml # use the callable deploy job
      secrets: inherit # pass all secrets for the environment
      with:
        container_tag: ${{ env.TARGET_TAG }}
        # >>>>>>>>>>>>>>> MODIFICATION FOR TESTING PURPOSES: production -> staging <<<<<<<<<<<<<<<
        environment: staging
