name: ci-main
run-name: ci-main
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  # Runs on all of the 'on' conditions above, including pull request events
  test-package:
    uses: ./.github/workflows/test_package.yml
  # Run this only on the main branch
  anchore-scan:
    uses: ./.github/workflows/anchore-scan.yml
    needs: [test-package]
    if: github.ref == 'refs/heads/main'
  # Run this only on the main branch
  tag-container-push:
    uses: ./.github/workflows/tag-container-push.yml
    needs: [test-package]
    if: github.ref == 'refs/heads/main'
