# Workflow for continuous integration tasks triggered on pushes to main and PRs to it and release

name: CI - Main and PRs
run-name: CI - Main and PRs
on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main", "release"]

jobs:
  test-python:
    uses: ./.github/workflows/job-test-python.yml
  test-gui:
    uses: ./.github/workflows/job-test-gui.yml
