# Pipeline to run tests on:
# - pushes to the main branch
# - pushes PRs to the main branch upon changes to certain files (see the 'paths:' list)

name: CI - Main and PRs
run-name: CI - Main and PRs
on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main", "release"]
    paths:
      [
        "**.py",
        "pyproject.toml",
        "**/c2x.sh",
        "**/atomsk.sh",
        "**/bin/**",
        "test_data/**",
      ]

jobs:
  test-python:
    uses: ./.github/workflows/job-test-python.yml
  test-gui:
    uses: ./.github/workflows/job-test-gui.yml
