# Workflow for continuous integration tasks triggered on pushes to main

name: CI - Main
run-name: CI - Main
on:
  workflow_dispatch:
    inputs:
      skip-tests:
        description: "Don't run tests before deploying"
        required: false
        default: false
        type: boolean
  push:
    branches: ["main"]

jobs:
  test-all:
    if: ${{ github.event_name == 'push' || ! github.event.inputs.skip-tests }}
    uses: ./.github/workflows/job-test-main.yml
    secrets: inherit # pass all secrets for the environment

  container-push:
    uses: ./.github/workflows/job-container-push.yml
    needs: [test-all]
    # Proceed if test-all was successful or skipped
    if: always() &&  (needs.test-all.result == 'skipped' || needs.test-all.result == 'success')
    with:
      # container_tag
      container_tag: ${{ github.sha }}
  # Deploy to Kubernetes Job - triggers remote workflow in private repo
  # Requires an environment, which is used downstream to consume environment specific secrets
  # from Vault, and to target the correct K8s manifests in the deploy/$environment directory hierarchy
  # For the tag, we need something unique for each push, so we use the SHA of the latest commit
  deploy-stfc-dev-k8s:
    needs: [container-push]
    # Proceed if test-all was successful or skipped
    if: always() && (needs.container-push.result == 'success')
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.DEPLOYMENT_APP_ID }}
          private-key: ${{ secrets.DEPLOYMENT_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: "psdi-data-conversion-deployment"

      - name: Trigger deployment workflow
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          gh api /repos/PSDI-UK/psdi-data-conversion-deployment/dispatches \
            --method POST \
            --field event_type=deploy \
            --field client_payload[tag]=${{ github.sha }} \
            --field client_payload[ref]=${{ github.ref }} \
            --field client_payload[repo]=${{ github.repository }} \
            --field client_payload[env]="development"

          echo "✅ Deployment triggered successfully"
          echo "Tag: ${{ github.sha }}"
          echo "Ref: ${{ github.ref }}"
          echo "Env: development"
