# Workflow for continuous integration tasks triggered on push to a release candidate branch

name: CI - Release candidate branches
run-name: CI - Release candidate branches
on:
  workflow_dispatch:
  push:
    branches: [ "rc**" ]
      
jobs:
  open-pull-request:
    # Open a PR if the branch isn't release itself
    if: ${{ github.head_ref || github.ref_name }} != 'release'
    uses: ./.github/workflows/job-open-pull-request.yml
    with:
      target: main
