# WARNING: Renaming this file will cause the deployment to PyPI and TestPyPI to fail until the new name is added to both
# in their Trusted Publisher Management (available in the in the Publishing section of the project management page)
#
# Workflow for continuous integration tasks triggered on push to release

name: CI - Release
run-name: CI - Release
on:
  workflow_dispatch:
  push:
    branches: ["release"]

jobs:
  test-python:
    uses: ./.github/workflows/job-test-python.yml
  test-gui:
    uses: ./.github/workflows/job-test-gui.yml

  # The commented out code below runs a code vulnerability scan on the
  # containerised app. This will not work on the free GitHub plan, since
  # for that plan code scanning is not supported for private repos - and
  # this is a private repo. There may be a work-around.
  #
  # NOTE: If you uncomment this job to use it you may wish to change the
  # 'needs' in the below 'tag-container-push' job from 'test-package'
  # to 'anchore-scan' if you want to make a release dependent on a successful
  # scan.
  #
  #anchore-scan:
  #  uses: ./.github/workflows/anchore-scan.yml
  #  needs: [test-package, test-gui]

  tag:
    uses: ./.github/workflows/job-tag.yml
    needs: [test-python, test-gui]

  container-push:
    uses: ./.github/workflows/job-container-push.yml
    needs: [tag]
    with:
      container_tag: ${{ needs.tag.outputs.container_tag }}

  publish-doc:
    needs: [tag]
    uses: ./.github/workflows/job-publish-doc.yml

  # Deploy to Kubernetes Job - triggers remote workflow in private repo
  # Requires an environment, which is used downstream to consume environment specific secrets
  # from Vault, and to target the correct K8s manifests in the deploy/$environment directory hierarchy
  deploy-stfc-staging-k8s:
    needs: [tag]
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.DEPLOYMENT_APP_ID }}
          private-key: ${{ secrets.DEPLOYMENT_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: "psdi-data-conversion-deployment"

      - name: Trigger deployment workflow
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          gh api /repos/PSDI-UK/psdi-data-conversion-deployment/dispatches \
            --method POST \
            --field event_type=deploy \
            --field client_payload[tag]=${{ needs.tag.outputs.container_tag }} \
            --field client_payload[ref]=${{ github.ref }} \
            --field client_payload[repo]=${{ github.repository }} \
            --field client_payload[env]="staging"

          echo "✅ Deployment triggered successfully"
          echo "Tag: ${{ needs.tag.outputs.container_tag }}"
          echo "Ref: ${{ github.ref }}"
          echo "Env: staging"

  build:
    needs: [tag]
    name: Build distribution 📦
    runs-on: psdi-data-conversion-runners

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install pypa/build
        run: >-
          python3 -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: python3 -m build
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  publish-to-testpypi:
    name: Publish Python 🐍 distribution 📦 to TestPyPI
    needs:
      - build
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/psdi-data-conversion

    permissions:
      id-token: write # IMPORTANT: mandatory for trusted publishing

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish distribution 📦 to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true
