name: tag-container-push
run-name: tag-container-push

#TU: TODO: A version label is not created in the git log? Is this an issue?

on:
#TU: limit to main branch only?
  push:


#TU: Not sure if the 'outputs' section below is needed
#  workflow_call:
#    outputs:
#      container_tag:
#        description: "Container Tag"
#        value: ${{ jobs.tag-container-push.outputs.container_tag }}


jobs:
  tag-container-push:
    outputs:
      container_tag: ${{ steps.tag_version.outputs.new_tag }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
      - name: Setup docker auth
        run: |
#TU: Fails on the runner I'm using so I've commented it out
#          mkdir ~/.docker
          cat <<EOF > ~/.docker/config.json
          {
            "auths": {
              "ghcr.io": {
                "auth": "$(echo -n "$GIT_USERNAME:$GIT_PASSWORD" | base64 -w0)"
              }
            }
          }
          EOF
        env: # needed to authenticate to github and download the repo
          GIT_USERNAME: ${{ github.actor }}
          GIT_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker build API
#TU: Need to change namespace from 'tomlunderwood/psdi-data-conversion' to 'psdi-uk/psdi-data-conversion'
        env:
          IMAGE_NAME: "ghcr.io/tomlunderwood/psdi-data-conversion/data-conversion:${{ steps.tag_version.outputs.new_tag }}"
        run: |
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

