# Pipeline to run automated tasks when feature branches are pushed to

name: Feature Push
run-name: Feature Push
on:
  workflow_dispatch:
  push:
    branches: [ "feature-**" ]
      
jobs:
  open-pull-request:
    # Open a PR if the branch isn't main itself
    if: ${{ github.head_ref || github.ref_name }} != 'main'
    uses: ./.github/workflows/open-pull-request.yml
    with:
      target: main
