# This workflow will automatically open a Pull Request when an applicable branch is pushed to

name: Open Pull Request
run-name: Open Pull Request
on:
  workflow_call:
    inputs:
      target:
        description: 'Branch to open a PR to'     
        required: false
        default: 'main'
        type: string
  workflow_dispatch:
    inputs:
      target:
        description: 'Branch to open a PR to'     
        required: false
        default: 'main'

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: create pull request
        id: create-pr
        run: |
          gh pr create -B ${{ inputs.target }} -H ${{ env.BRANCH_NAME }} --title \
            'Merge ${{ env.BRANCH_NAME }} into ${{ inputs.target }}' --body '' \
            && SUCCESS=1 || SUCCESS=0
          if [ $SUCCESS -eq 1 ]; then
            echo "Pull request successfully created"
          else
            echo "Pull request already exists"
            echo "run_tests=0" >> $GITHUB_OUTPUT
          fi
          # For merges to release, we don't need to additionally run tests here
          if [ ${{ inputs.target }} -eq release ]; then
            RUN_TESTS=0
          else
            RUN_TESTS=$SUCCESS
          fi
          echo "run_tests=$RUN_TESTS" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      is_new: ${{ steps.create-pr.outputs.is_new }}
          
  test-package:
    needs: create-pr
    uses: ./.github/workflows/test-python.yml
    if: needs.create-pr.outputs.is_new == '1'
    
  test-gui:
    needs: create-pr
    uses: ./.github/workflows/test-gui.yml
    if: needs.create-pr.outputs.is_new == '1'
