# Runs tests by invoking a script

# TODO: Specify a specific version of Python and selenium to use for testing

name: run-tests
run-name: run-tests

on:
  push:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5 
        with:
          python-version: '3.9'
      - name: Install selenium
        run: pip install selenium
      - name: Run tests
        run: python run_tests.py

