name: Update Common Assets

on:
  schedule:
    # Run once a month
    - cron: "00 0 1 * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-assets:
    name: Update common assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch assets
        run: |
          ./scripts/fetch-common-style.sh
          ./scripts/make-index-html.sh

      - name: Commit and push updated assets
        run: |
          git config --global user.name 'PSDI Automated Workflow'
          git config --global user.email 'psdi@users.noreply.github.com'
          git commit -am "Automated update of metadata vocab" && git push || echo "No changes to commit"
